import { expect, test } from '@playwright/test'

test('拖曳結果文字與插畫不選取或啟動拖圖，分享網址仍可手動選取', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(navigator, 'clipboard', { value: undefined, configurable: true }) })
  await page.goto('./#/result/v1/low-battery-helper')
  const title = await page.getByRole('heading', { level: 1 }).boundingBox()
  expect(title).not.toBeNull()
  await page.mouse.move(title!.x + 2, title!.y + title!.height / 2)
  await page.mouse.down()
  await page.mouse.move(title!.x + title!.width - 2, title!.y + title!.height / 2, { steps: 15 })
  await page.mouse.up()
  expect(await page.evaluate(() => window.getSelection()?.toString())).toBe('')
  const mascot = page.locator('.mascot')
  await expect(mascot).toHaveAttribute('draggable', 'false')
  await mascot.evaluate((image) => { image.addEventListener('dragstart', () => image.setAttribute('data-drag-started', 'true')) })
  const imageBox = (await mascot.boundingBox())!
  await page.mouse.move(imageBox.x + imageBox.width / 2, imageBox.y + imageBox.height / 2)
  await page.mouse.down()
  await page.mouse.move(imageBox.x + imageBox.width / 2 + 70, imageBox.y + imageBox.height / 2 + 40, { steps: 12 })
  await page.mouse.up()
  await expect(mascot).not.toHaveAttribute('data-drag-started', 'true')
  await page.getByRole('link', { name: '分享說明書', exact: true }).click()
  await page.getByRole('button', { name: '複製連結' }).click()
  const urlInput = page.getByLabel('請選取下方網址，手動複製分享。')
  await urlInput.focus()
  expect(await urlInput.evaluate((input: HTMLInputElement) => input.selectionEnd! - input.selectionStart!)).toBe((await urlInput.inputValue()).length)
})

test('首頁重新開始與關於頁清除作答使用頁內確認，取消不清除答案', async ({ page }) => {
  const nativeDialogs: string[] = []
  page.on('dialog', async (dialog) => { nativeDialogs.push(dialog.message()); await dialog.dismiss() })
  await page.goto('./')
  await page.getByRole('button', { name: '開始翻開我的說明書' }).click()
  await page.getByRole('radio').first().check()
  await page.getByRole('link', { name: '人類使用說明書', exact: true }).click()
  await page.getByRole('button', { name: '重新開始', exact: true }).click()
  const restartDialog = page.getByRole('dialog', { name: '重新翻開一頁？' })
  await restartDialog.getByRole('button', { name: '先保留' }).click()
  await page.getByRole('button', { name: '繼續這次測驗' }).click()
  await expect(page.getByRole('radio').first()).toBeChecked()
  await page.getByRole('link', { name: '關於這份說明書', exact: true }).click()
  await page.getByRole('button', { name: '清除這次作答' }).click()
  const clearDialog = page.getByRole('dialog', { name: '把這一頁留白？' })
  await expect(clearDialog).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(clearDialog).not.toBeVisible()
  await expect(page.getByRole('button', { name: '清除這次作答' })).toBeFocused()
  await page.getByRole('button', { name: '清除這次作答' }).click()
  await clearDialog.getByRole('button', { name: '清除作答', exact: true }).click()
  await expect(page.getByRole('button', { name: '開始翻開我的說明書' })).toBeVisible()
  await expect(page.getByRole('button', { name: '繼續這次測驗' })).toHaveCount(0)
  expect(nativeDialogs).toEqual([])
})
